language: java
jdk:
  - oraclejdk8

##
# Each matrix * global item is a new test/build/deploy path.
# @link: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
##

env:
  global:
    - platform="templateecs"
    - stage="prod"
    - repo="reponame"
    - ecr_host="12345678910.dkr.ecr.us-east-1.amazonaws.com"
  matrix:
    - mservice="api1" port="8033"
    - mservice="api2" port="8034"

before_install:
  - sudo sh -c "curl -O https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz"
  - sudo sh -c "tar -xvf docker-1.11.2.tgz"
  - sudo sh -c "sudo mv docker/docker /usr/bin/"

install:
  - sudo apt-get install python-pip
  - sudo pip install awscli

before_script:
  - chmod +x infra/*.sh

script:
  - ./infra/build.sh ${TRAVIS_BRANCH} ${platform} ${mservice} ${port} ${stage}

deploy:
  - provider: script
    script: ./infra/deploy.sh ${TRAVIS_BRANCH} ${platform} ${mservice} ${port} ${stage}
    skip_cleanup: true
    on:
      repo: ${repo}
      branch: deploy